### ISSUE TITLE
Increase Memory of VM

### ISSUE THREAD

**Issue by lakshanthad** [ptrsr/pi-ci#13]
Hi,

Thank you for the great work on this project!

Currently, the VM has only 2GB of memory. Is it possible to increase this to 8GB. Thanks.

<img src="https://github.com/user-attachments/assets/f79482c1-097f-425c-beca-aa2cce18e8dd" width=400>

**Comment by IvoKara** [comment]
As I was searching for something in the codebase I [came to this line](https://github.com/ptrsr/pi-ci/blob/master/src/app/func/start.py#L46) which I think answers your question. Maybe you should change the value of the `-m` flag of the `qemu-system-aarch64` command that is executed underneath and build the docker image again by yourself.

**Comment by lakshanthad** [comment]
Thank you @IvoKara. It worked!

**Comment by ptrsr** [comment]
Hi @lakshanthad ,

Thanks for your interest. I'm glad that @IvoKara could help you out! I'm planning to make this a command line argument so that you can easily change the amount of RAM. I'm currently on vacation, so it'll have to wait a couple weeks.

Best,
R.

**Comment by lakshanthad** [comment]
@ptrsr That would be great! Looking forward to the command-line arguments! Have a great vacation :)
