### ISSUE TITLE
How to use with armhf version Raspberry Pi OS?

### ISSUE THREAD

**Issue by CRT-HAO** [ptrsr/pi-ci#4]
How to use with armhf version Raspberry Pi OS?

**Comment by ptrsr** [comment]
This highly depends on your goals. Note that this repository is not finished and will need some adjustment to fully support `armhf` and different target platforms such as the Pi Nano. To put it concisely; the current QEMU version supports running RPI3 `armhf` images but does not come with one. You will have to create one yourself.

The current dockerfile builds an `arm64` image. It should be possible to change this to `armhf`. I might add such a build later, for now you'll have to do it by changing some variables in the `dockerfile` and building the image yourself. To get you started, here's an example:

```
ARG DISTRO_FILE=2021-10-30-raspios-bullseye-armhf-lite
ARG DISTRO_IMG=https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/$DISTRO_FILE.zip
ARG KERNEL=kernel7
ARG ARCH=arm
CROSS_COMPILE=arm-linux-gnueabihf-
```
Note that these variables depend on your target platform (e.g. raspi2, 3, nano). You can find more information on kernel building [here](https://www.raspberrypi.com/documentation/computers/linux_kernel.html).

in addition, you'll need to change `crossbuild-essential-arm64` to `crossbuild-essential-armhf`.
And lastly (and probably a somewhat difficult step) is to change the kernel `.config`. This highly depends on your target platform. I've used `bcm2711_defconfig` as this version targets the PI4 but you might want to use another one.
