### ISSUE TITLE
Pi Zero W & Pi Zero 2 W support?

### ISSUE THREAD

**Issue by foobarbecue** [ptrsr/pi-ci#7]
Do you plan to support the Zero models?

**Comment by ptrsr** [comment]
Hi @foobarbecue , thanks for your interest in the project.
The Pi Zero 2 may already be supported, but I haven't tested it yet. It runs on the same architecture (`ARMv8`) as the Pi 3 & 4. So although the virtual machine runs the image as a RPi 3, the resulting image should be compatible with the PI Zero 2. 

The Zero 1 runs on `ARMv6`, which isn't compatible with the `ARMv8 64 bit` base image that is build in the PI-CI pipeline. However, with some tweaking, the PI-CI pipeline could build and run a `ARMv6 32bit` bit image.  I won't be building it myself, but I wouldn't mind helping out if someone decides to fork this project.

If you or someone else could confirm Pi Zero 2 support, that'd be great.
